const env = import.meta.env;

export const URL_SERVER_USER = env?.VITE_URL_SERVER_USER
export const CLAVE_SERVER_USER_GET = env?.VITE_CLAVE_SERVER_USER_GET
export const CLAVE_SERVER_USER_POST = env?.VITE_CLAVE_SERVER_USER_POST
export const PASSWORD_LOGIN = env?.VITE_PASSWORD_LOGIN